d = input('Digite algo: ')
print('Seu tipo primitivo é: ', type(d))
print('É um número:', d.isnumeric())
print('É alfabético:', d.isalpha())
print('É alfanumerico:', d.isalnum())
print('Contem apenas letras e/ou numeros:', d.isascii())
print('Contem todos os dígitos decimais:', d.isdecimal())
print('Contem somente digitos:', d.isdigit())
print('O objeto string forma um identificador válido:', d.isidentifier())
print('É formado apenas por caracteres maiusculos:', d.isupper())
print('Começa com letra maiuscula:', d.istitle())
print('Só tem espaços:', d.isspace())
print('A sequência esta vazia:', d.isprintable())
print('É formado apenas por caracteres minusculos:', d.islower())
