ni = int(input('Digite um número inteiro: '))
print('Tabuada do número {}: '.format(ni))
print('='*60)
print('   Adição     |    Subtração  |  Multiplição |     Divisão      |')
print('{} + 1 = {}   |  {} - 1 = {}  | {} x 1 = {}  | {} / 1 = {:.3f}  |'.format(ni, ni+1, ni, ni-1, ni, ni*1, ni, ni/1))
print('{} + 2 = {}   |  {} - 2 = {}  | {} x 2 = {}  | {} / 2 = {:.3f}  |'.format(ni, ni+2, ni, ni-2, ni, ni*2, ni, ni/2))
print('{} + 3 = {}   |  {} - 3 = {}  | {} x 3 = {}  | {} / 3 = {:.3f}  |'.format(ni, ni+3, ni, ni-3, ni, ni*3, ni, ni/3))
print('{} + 4 = {}   |  {} - 4 = {}  | {} x 4 = {}  | {} / 4 = {:.3f}  |'.format(ni, ni+4, ni, ni-4, ni, ni*4, ni, ni/4))
print('{} + 5 = {}   |  {} - 5 = {}  | {} x 5 = {}  | {} / 5 = {:.3f}  |'.format(ni, ni+5, ni, ni-5, ni, ni*5, ni, ni/5))
print('{} + 6 = {}   |  {} - 6 = {}  | {} x 6 = {}  | {} / 6 = {:.3f}  |'.format(ni, ni+6, ni, ni-6, ni, ni*6, ni, ni/6))
print('{} + 7 = {}   |  {} - 7 = {}  | {} x 7 = {}  | {} / 7 = {:.3f}  |'.format(ni, ni+7, ni, ni-7, ni, ni*7, ni, ni/7))
print('{} + 8 = {}   |  {} - 8 = {}  | {} x 8 = {}  | {} / 8 = {:.3f}  |'.format(ni, ni+8, ni, ni-8, ni, ni*8, ni, ni/8))
print('{} + 9 = {}   |  {} - 9 = {}  | {} x 9 = {}  | {} / 9 = {:.3f}  |'.format(ni, ni+9, ni, ni-9, ni, ni*9, ni, ni/9))
print('{} + 10 = {}  |  {} - 10 = {} | {} x 10 = {} | {} / 10 = {:.3f} |'.format(ni,ni+10, ni, ni-10, ni,ni*10, ni, ni/10))
print('='*60)